### ISSUE TITLE
UML Diagram for Datamodel

### ISSUE THREAD

**Issue by schmidni** [swiss-seismological-service/esloss.datamodel#1]
### User Story
As a user or developer of the software I would like to have a UML diagram describing the datamodel so that I can more easily understand what's going on.

### Acceptance Criteria
An easily editable and clear UML diagram of the database models as they are used/set up in SQLAlchemy.

### Tasks
- [x] Find and set up appropriate software
- [x] Read up on correct notation / UML terminology
- [x] Create the actual diagram

**Comment by schmidni** [comment]
added here: eee3f9ce88b91b32fb3c890c55d4758d842f70ff

https://lucid.app/lucidchart/ff7b1e64-a2f6-4d6b-8a65-573a59e0bf73/edit?viewport_loc=-105%2C-165%2C3415%2C1172%2CHWEp-vi-RSFO&invitationId=inv_76821072-f133-465d-9311-a813d12239c0#
